### ISSUE TITLE
I can't jump to definition (java)

### ISSUE THREAD

**Issue by 1Jo1** [baobaoit/beande#35]
Hii,

I'm trying to use your nvim config, but I cannot figure out, how to jump to vim.lsp.buf.definition() in java files, however jdtls seems to work, I just changed some paths here https://github.com/baobaoit/beande/blob/main/ftplugin/java.lua
jump to definition, does it work for you?

**Comment by baobaoit** [comment]
Hi @1Jo1,

Yes, it works for me with my current config.

https://user-images.githubusercontent.com/31947091/197588923-80969061-c3a3-4bd0-861e-e030d7073906.mov

**Comment by baobaoit** [comment]
Hi @1Jo1,

Here is explain of some paths:

This is where the `JDK 8` home path (starts from the HOME directory):
https://github.com/baobaoit/beande/blob/cf6787dcb0ced1af2479e2eff944f3ecb38cb75e/ftplugin/java.lua#L6-L7

If you don't use it, you can comment like this:
```lua
 -- local jabba_jdk_dir = home_dir..'/.jabba/jdk/' 
 -- local jdk8_dir = jabba_jdk_dir..'1.8.0/Contents/Home' 
```

And also on these lines:
https://github.com/baobaoit/beande/blob/cf6787dcb0ced1af2479e2eff944f3ecb38cb75e/ftplugin/java.lua#L99-L104

Apologies that you have faced this issue when using my config, as it is still in development so I don't know how to write the README.md like.

If you have any questions, please let me know below.

Best regards.

Thank you.

**Comment by 1Jo1** [comment]
Hi @baobaoit,

cool thanks, yeah I just removed JDK 8, but now I'm getting message when I'm trying to jump to definition the first time, however the second time jump works which is weird

I record a small video [here](https://asciinema.org/a/5b2kgxmBLDEBZa6ACQfvg5Qca), there are two different jumps:
- inside this project AccountService
- HashMap

BTW after the jump: I'm not quite sure why syntax highlighting doesnt work anymore

**Comment by 1Jo1** [comment]
this is the error message
```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:1092: Vim(append):Error executing lua callback: /usr/share/nvim/runtime/filetype.lua:22: Error executing lua: /usr/share/nvim/runtime/filetype.lua:23: Vim(runtime):E5113: Error while ca
lling lua chunk: .../pack/packer/start/which-key.nvim/lua/which-key/keys.lua:174: Vim:No LSP client found that supports vscode.java.resolveMainClass
stack traceback:
        [C]: in function 'nvim_buf_call'
        .../pack/packer/start/which-key.nvim/lua/which-key/keys.lua:174: in function 'map'
        .../pack/packer/start/which-key.nvim/lua/which-key/keys.lua:205: in function 'register'
        .../pack/packer/start/which-key.nvim/lua/which-key/init.lua:73: in function 'register'
        /home/jo/.config/nvim/ftplugin/java.lua:155: in main chunk
        [C]: in function 'nvim_cmd'
        /usr/share/nvim/runtime/filetype.lua:23: in function </usr/share/nvim/runtime/filetype.lua:22>
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/filetype.lua:11>
        [C]: in function 'nvim_set_current_buf'
        /usr/share/nvim/runtime/lua/vim/lsp/util.lua:1092: in function 'jump_to_location'
        /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:359: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1390: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
stack traceback:
        [C]: in function 'nvim_cmd'
        /usr/share/nvim/runtime/filetype.lua:23: in function </usr/share/nvim/runtime/filetype.lua:22>
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/filetype.lua:11>
        [C]: in function 'nvim_set_current_buf'
        /usr/share/nvim/runtime/lua/vim/lsp/util.lua:1092: in function 'jump_to_location'
        /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:359: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1390: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
stack traceback:
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/filetype.lua:11>
        [C]: in function 'nvim_set_current_buf'
        /usr/share/nvim/runtime/lua/vim/lsp/util.lua:1092: in function 'jump_to_location'
        /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:359: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1390: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
stack traceback:
        [C]: in function 'nvim_set_current_buf'
        /usr/share/nvim/runtime/lua/vim/lsp/util.lua:1092: in function 'jump_to_location'
        /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:359: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1390: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by 1Jo1** [comment]
thats my neovim config diff
```
diff --git a/ftplugin/java.lua b/ftplugin/java.lua
index 6d38f52..53c17d6 100644
--- a/ftplugin/java.lua
+++ b/ftplugin/java.lua
@@ -2,9 +2,9 @@
 local fn = vim.fn
 local project_name = fn.fnamemodify(fn.getcwd(), ':p:h:t')

-local home_dir = os.getenv('HOME')
-local jabba_jdk_dir = home_dir..'/.jabba/jdk/'
-local jdk8_dir = jabba_jdk_dir..'1.8.0/Contents/Home'
+local home_dir = '/home/jo'
+--local jabba_jdk_dir = home_dir..'/.jabba/jdk/'
+--local jdk8_dir = jabba_jdk_dir..'1.8.0/Contents/Home'
 local nvim_dir = home_dir..'/.config/nvim'
 local rule_dir = nvim_dir..'/rule/'
 local java_settings_url = rule_dir..'settings.prefs'
@@ -92,17 +92,6 @@ local config = {
   settings = {
     ['java.settings.url'] = java_settings_url,
     java = {
-      configuration = {
-        -- See https://github.com/eclipse/eclipse.jdt.ls/wiki/Running-the-JAVA-LS-server-from-the-command-line#initialize-request
-        -- And search for `interface RuntimeOption`
-        -- The `name` is NOT arbitrary, but must match one of the elements from `enum ExecutionEnvironment` in the link above
-        runtimes = {
-          {
-            name = 'JavaSE-1.8',
-            path = jdk8_dir
-          }
-        }
-      },
       codeGeneration = {
         hashCodeEquals = {
           useInstanceof = true,
```

**Comment by 1Jo1** [comment]
whats is your jdtls cmd https://github.com/baobaoit/beande/blob/main/ftplugin/java.lua#L58 configuration?

**Comment by baobaoit** [comment]
Hi @1Jo1,

Here is my video when I use my neovim with my config on your demo:
https://drive.google.com/file/d/1KpsgYVIjRZz0KuGbQyAlym7WwBkuDZnh/view?usp=sharing

This explains my jdtls configuration on:
https://github.com/baobaoit/beande/blob/cf6787dcb0ced1af2479e2eff944f3ecb38cb75e/ftplugin/java.lua#L58-L74

- The `'jdtls'` inside the table `cmd { }` is the command `jdtls` (Java Language Server Protocol) (the repo [here](https://github.com/eclipse/eclipse.jdt.ls)), that I have installed through Mason (the repo [here](https://github.com/williamboman/mason.nvim))
  https://github.com/baobaoit/beande/blob/cf6787dcb0ced1af2479e2eff944f3ecb38cb75e/lua/plugins/mason-eco/mason-lspconfig.lua#L7

- From lines 64 to 69 is the configuration for Lombok (if the current project uses it). If you don't know what Lombok is, then you can reference this: https://projectlombok.org/
- From lines 73 to 74 is the configuration for the project workspace (like the Eclipse IDE)

1 issue on your demo project is these classes are under the service package is wrong package (missing `.service`)
- AccountService.java: current is `package com.example.demo;` --> `package com.example.demo.service;`
  <img width="882" alt="image" src="https://user-images.githubusercontent.com/31947091/197917348-9816bd64-29ef-455a-bfe0-4c769e013258.png">

- TestService.java: current is `package com.example.demo;` --> `package com.example.demo.service;`
  <img width="873" alt="image" src="https://user-images.githubusercontent.com/31947091/197917496-e8eef0ac-1b3c-4746-956d-8288f5f08ff1.png">

Another place that uses `os.getenv('HOME')` is: 
https://github.com/baobaoit/beande/blob/cf6787dcb0ced1af2479e2eff944f3ecb38cb75e/lua/bootstrap/init.lua#L20-L24

Can you try to edit line 20? And try again.

Sorry, I don't have Linux to test, and I currently develop it on my Mac.

If you have any questions, please let me know below.

Best regards.

Thank you.

**Comment by baobaoit** [comment]
Hi @1Jo1 

For the syntax highlighting issue:
> BTW after the jump: I'm not quite sure why syntax highlighting doesnt work anymore

Please check the nvim-treesitter repo: https://github.com/nvim-treesitter/nvim-treesitter

**Comment by 1Jo1** [comment]
> Hi @1Jo1,
> 
> Here is my video when I use my neovim with my config on your demo: https://drive.google.com/file/d/1KpsgYVIjRZz0KuGbQyAlym7WwBkuDZnh/view?usp=sharing
> 
> This explains my jdtls configuration on:
> 
> https://github.com/baobaoit/beande/blob/cf6787dcb0ced1af2479e2eff944f3ecb38cb75e/ftplugin/java.lua#L58-L74
> 
> * The `'jdtls'` inside the table `cmd { }` is the command `jdtls` (Java Language Server Protocol) (the repo [here](https://github.com/eclipse/eclipse.jdt.ls)), that I have installed through Mason (the repo [here](https://github.com/williamboman/mason.nvim))
>   https://github.com/baobaoit/beande/blob/cf6787dcb0ced1af2479e2eff944f3ecb38cb75e/lua/plugins/mason-eco/mason-lspconfig.lua#L7
> * From lines 64 to 69 is the configuration for Lombok (if the current project uses it). If you don't know what Lombok is, then you can reference this: https://projectlombok.org/
> * From lines 73 to 74 is the configuration for the project workspace (like the Eclipse IDE)
> 
> 1 issue on your demo project is these classes are under the service package is wrong package (missing `.service`)
> 
> * AccountService.java: current is `package com.example.demo;` --> `package com.example.demo.service;`
>   <img alt="image" width="882" src="https://user-images.githubusercontent.com/31947091/197917348-9816bd64-29ef-455a-bfe0-4c769e013258.png">
> * TestService.java: current is `package com.example.demo;` --> `package com.example.demo.service;`
>   <img alt="image" width="873" src="https://user-images.githubusercontent.com/31947091/197917496-e8eef0ac-1b3c-4746-956d-8288f5f08ff1.png">
> 
> Another place that uses `os.getenv('HOME')` is:
> 
> https://github.com/baobaoit/beande/blob/cf6787dcb0ced1af2479e2eff944f3ecb38cb75e/lua/bootstrap/init.lua#L20-L24
> 
> Can you try to edit line 20? And try again.
> 
> Sorry, I don't have Linux to test, and I currently develop it on my Mac.
> 
> If you have any questions, please let me know below.
> 
> Best regards.
> 
> Thank you.

I do have lombok installed and I fixed home directory [beande/lua/bootstrap/init.lua](https://github.com/baobaoit/beande/blob/cf6787dcb0ced1af2479e2eff944f3ecb38cb75e/lua/bootstrap/init.lua#L20-L24) and this package com.example.demo.service , but I still have same issue...

**Comment by 1Jo1** [comment]
> Hi @1Jo1
> 
> For the syntax highlighting issue:
> 
> > BTW after the jump: I'm not quite sure why syntax highlighting doesnt work anymore
> 
> Please check the nvim-treesitter repo: https://github.com/nvim-treesitter/nvim-treesitter

yeah I know, I didn't find anything there to fix that, but only happens when I'm jumping(you can actually see that on the video)

**Comment by baobaoit** [comment]
Hi @1Jo1,

Please run these commands:
1. Install `tree-sitter-cli`
  ```cmd
  npx yarn global add tree-sitter-cli
  ```
2. Go to the folder `~/.config/nvim`
  ```cmd
  git submodule init && git submodule update
  ```
3. Build `fernflower`
  ```cmd
  cd pack/fernflower && ./gradlew clean build -x test
  ```
4. When finished, your current directory is `~/.config/nvim/pack/fernflower`, now we will build the `java-debug`
  ```cmd
  cd ../java-debug && ./mvnw clean install -DskipTests
  ```

Temporarily, I am stuck on the step run `./mvnw clean install -DskipTests` on my Ubuntu (runs on a Docker container), I will update it later.

Best regards.

Thank you.

**Comment by 1Jo1** [comment]
> Hi @1Jo1,
> 
> Please run these commands:
> 
> 1. Install `tree-sitter-cli`
> 
> ```batchfile
> npx yarn global add tree-sitter-cli
> ```
> 
> 2. Go to the folder `~/.config/nvim`
> 
> ```batchfile
> git submodule init && git submodule update
> ```
> 
> 3. Build `fernflower`
> 
> ```batchfile
> cd pack/fernflower && ./gradlew clean build -x test
> ```
> 
> 4. When finished, your current directory is `~/.config/nvim/pack/fernflower`, now we will build the `java-debug`
> 
> ```batchfile
> cd ../java-debug && ./mvnw clean install -DskipTests
> ```
> 
> Temporarily, I am stuck on the step run `./mvnw clean install -DskipTests` on my Ubuntu (runs on a Docker container), I will update it later.
> 
> Best regards.
> 
> Thank you.

@baobaoit 
cool thanks, I will try that now, I will let you know later
i am very grateful that you are trying it out on linux, some of my friends are using https://github.com/lima-vm/lima which is amazing according to them, its a vm not a container and its super fast(containerd)

**Comment by baobaoit** [comment]
Hi @1Jo1 ,

After ran these commands above the syntax highlighting is resolved.

Currently, I figured out that these lines cause the issue when you jump to the definition
https://github.com/baobaoit/beande/blob/cf6787dcb0ced1af2479e2eff944f3ecb38cb75e/ftplugin/java.lua#L165-L204

I try to comment out and it works perfectly, I will try to fix it on Linux environment.

**Comment by 1Jo1** [comment]
@baobaoit 
thank you so much, the issue was I didnt pay much attention to the lsp log ``` :JdtShowLogs``` I saw some weird errors, so removed the workspace directory in nvim folder, now it works 😇
all kind of jumps works fine I dont have any issue, I saw in ':JdtShowLogs' one error

have you ever had this issue? if not I will try to look closer tomorrow, its not super important
it could be related this issue maybe https://github.com/mfussenegger/nvim-jdtls/issues/291

```
java.lang.NoClassDefFoundError: javax/annotation/processing/AbstractProcessor
	at java.base/java.lang.ClassLoader.findBootstrapClass(Native Method)
	at java.base/java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1262)
	at java.base/java.lang.System$2.findBootstrapClassOrNull(System.java:2310)
	at java.base/jdk.internal.loader.ClassLoaders$BootClassLoader.loadClassOrNull(ClassLoaders.java:140)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:676)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:676)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:574)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:574)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.eclipse.jdt.apt.core.internal.AnnotationProcessorFactoryLoader.loadJava6FactoryClasses(AnnotationProcessorFactoryLoader.java:641)
	at org.eclipse.jdt.apt.core.internal.AnnotationProcessorFactoryLoader.loadFactories(AnnotationProcessorFactoryLoader.java:580)
	at org.eclipse.jdt.apt.core.internal.AnnotationProcessorFactoryLoader.getJava6FactoriesAndAttributesForProject(AnnotationProcessorFactoryLoader.java:458)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:134)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:953)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:450)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:379)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:214)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:311)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:79)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:273)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:193)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1024)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:254)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:311)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:400)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:403)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:514)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:462)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:544)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:161)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:255)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by 1Jo1** [comment]
> Hi @1Jo1 ,
> 
> After ran these commands above the syntax highlighting is resolved.
> 
> Currently, I figured out that these lines cause the issue when you jump to the definition
> 
> https://github.com/baobaoit/beande/blob/cf6787dcb0ced1af2479e2eff944f3ecb38cb75e/ftplugin/java.lua#L165-L204
> 
> I try to comment out and it works perfectly, I will try to fix it on Linux environment.

now it works 😍 thank you

**Comment by baobaoit** [comment]
Hi @1Jo1 ,

For my previous comment: https://github.com/baobaoit/beande/issues/35#issuecomment-1292198346
This is **NOT** the root cause, after a few minutes to debug and reference this comment: https://github.com/redhat-developer/vscode-java/issues/652#issuecomment-466906125

Finally, I have figured out the root cause is:
https://github.com/baobaoit/beande/blob/cf6787dcb0ced1af2479e2eff944f3ecb38cb75e/ftplugin/java.lua#L68

I commented on it and everything is working fine on my Linux:
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/31947091/198077905-7345cf24-796c-4346-8a0f-273c72307684.png">

As you can see here: https://projectlombok.org/changelog
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/31947091/198078368-5c095c46-558c-49d1-a230-899132acc8a2.png">

I will try to fix it and test it on both Linux and Mac.

I'm glad that you have found my repo, used it, and given me feedback.

Best regards.

Thank you.

**Comment by 1Jo1** [comment]
@baobaoit thanks I just tested that, thanks for fixing it :+1:
